AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Model accounts Api Assets

Parameters:

  DNSName:
    Type: String
    Description: Name of Moodle API route 53 entry to use for target

  HostedZoneName:
    Type: String
    Description: Name of existing route 53 hosted zone name

  TableBaseName:
    Type: String
    Description: Name of the base table name for dynamodb

  Stage:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
    Default: dev
    Description: Stage that can be added to resource names

Resources:

  AccountsCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub ${Stage}.${DNSName}

  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref AccountsCertificate
      DomainName: !Sub ${Stage}.${DNSName}

  LambdaDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName:
        Ref: HostedZoneName
      Comment: Zone apex alias targeted to ApiGateway
      RecordSets:
      - Name: !Sub ${Stage}.${DNSName}.
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # This is hardcoded for all CloudFormation templates
          DNSName: !GetAtt DomainName.DistributionDomainName

  # Application assets
  AccountsHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.moodle.account.LambdaHandler
      FunctionName: !Sub AccountsHandler_${Stage}
      MemorySize: 1024
      Runtime: java8
      CodeUri: target/moodle-accounts-1.0.jar
      Timeout: 15
      Environment:
        Variables:
          TABLE_NAME: !Sub ${TableBaseName}_${Stage}
          ENVIRONMENT: !Ref Stage
          POST_TENANT_URL: !Sub https://api.vssdevelopment.com/${Stage}/moodle/tenants
      Role: !GetAtt LambdaRole.Arn
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

  #API Gateway definition
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Ref AWS::StackName
        basePath: /prod
        schemes:
        - https
        paths:
          /:
            x-amazon-apigateway-any-method:
              produces:
              - application/json
              responses:
                "200":
                  description: 200 response
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AccountsHandler.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
            options:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                "200":
                  description: 200 response
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                type: mock
          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
              - application/json
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AccountsHandler.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
            options:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                "200":
                  description: 200 response
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
              x-amazon-apigateway-integration:
                contentHandling: CONVERT_TO_TEXT
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                type: mock
        x-amazon-apigateway-binary-media-types:
          - '*/*'
        definitions:
          Empty:
            type: object
            title: Empty Schema

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - "dynamodb:DeleteItem"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:Scan"
            - "dynamodb:UpdateItem"
            Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MoodleAccountsTable}/*



  AccountsHandlerVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName:
        Ref: AccountsHandler
      Description: Most recent published version

#############################################
##  Define Environment Specific API Gateway,
##  Lambda, and Dynamodb resources
#############################################
#  Deployment:
#    Type: AWS::ApiGateway::Deployment
#    Properties:
#      Description: !Sub Deployment for ${Stage}
#      RestApiId: !Ref ApiGateway
#      StageName: !Ref Stage

#  ApiGatewayStage:
#    Type: AWS::ApiGateway::Stage
#    Properties:
#      StageName: !Ref Stage
#      RestApiId: !Ref ApiGateway
#      DeploymentId: !Ref Deployment
#      Variables:
#        env: !Ref Stage
#      #note-this requires api gateway to have appropriate role
#      MethodSettings:
#        - DataTraceEnabled: true
#          HttpMethod: "*"
#          LoggingLevel: INFO
#          ResourcePath: "/*"
#          MetricsEnabled: true
##
  UrlMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref ApiGateway
      Stage: !Ref Stage

  MoodleAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "email"
          KeyType: "HASH"
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
#      GlobalSecondaryIndexes:
#        -
#          IndexName: "id-index"
#          KeySchema:
#            -
#              AttributeName: "id"
#              KeyType: "HASH"
#          Projection:
#            ProjectionType: "ALL"
#          ProvisionedThroughput:
#            ReadCapacityUnits:
#              Ref: 1
#            WriteCapacityUnits:
#              Ref: 1
      TableName: !Sub ${TableBaseName}_${Stage}

#output
Outputs:
  AccountsCertificate:
    Value: !Ref AccountsCertificate
    Export:
      Name: !Sub AccountsCertificate-${Stage}

  AccountsApiGatewayRef:
    Value: !Ref ApiGateway
    Export:
      Name: !Sub AccountsApiGatewayRef-${Stage}

  AccountsHandlerArn:
    Value: !GetAtt AccountsHandler.Arn
    Export:
      Name: !Sub AccountsHandlerArn-${Stage}

  AccountsHandlerVersion:
    Value: !GetAtt AccountsHandlerVersion.Version
    Export:
      Name: !Sub AccountsHandlerVersion-${Stage}
